---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: WebIdentity
    webIdentity:
      roleARN: "arn:aws:iam::381491847637:role/gitops-management-services-crossplane-irsa"
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: 590184126528-crossplane-bucket
  namespace: iac-bucket
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: us-east-1