---
controller:
  kind: Deployment
  allowSnippetAnnotations: true

  service:
    enabled: true
    type: LoadBalancer
    annotations:
      service.k8s.aws/load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"

  serviceAccount:
    create: false
    name: ingress-nginx
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::905418304539:role/cpe-application-dev-services-ingress-nginx-irsa
