apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 8.6.4
    releaseName: grafana
    valuesFile: values.yaml
