---
fullnameOverride: ingress-nlb
controller:
  kind: DeamonSet
  replicaCount: 3
  allowSnippetAnnotations: true
  metrics:
    enabled: true
  podAnnotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 90Mi