---
fullnameOverride: ingress-nlb
controller:
  kind: DaemonSet
  #replicaCount: 3
  allowSnippetAnnotations: false
  metrics:
    enabled: true
  podAnnotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 90Mi
  nodeSelector:
    kubernetes.io/os: linux
  affinity: {}
  topologySpreadConstraints: []