---
fullnameOverride: metrics-server
replicas: 3
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
metrics:
  enabled: true
serviceMonitor:
  enabled: true
  interval: 1m
  scrapeTimeout: 10s
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: metrics-server
