---
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: 590184126528-1-crossplane-bucket
  namespace: iac-bucket
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: us-east-1