apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-nginx-forwarding-alb"
  namespace: "ingress-nginx"
  labels:
    app: "ingress-nginx-forwarding-alb"
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
    alb.ingress.kubernetes.io/target-type: "instance"
    alb.ingress.kubernetes.io/subnets: subnet-0632cb1f9c96b97b2,subnet-03084ff8a28b1140f,subnet-0d878d1037e279c7d
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:381492233961:certificate/12668263-c51f-417e-89fe-5f6d62e5c111"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/success-codes: "200,404"
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "ssl-redirect"
            port:
              name: use-annotation
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "ingress-nginx-controller"
            port:
              number: 80