# values.yaml para Metrics Server

# Configurações gerais
global:
  # Definindo o limite de recursos, adequado para um ambiente de desenvolvimento
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Configurações específicas do Metrics Server
metrics-server:
  # Habilitar ou desabilitar o Metrics Server
  enabled: true

  # Configurações de imagem
  image:
    repository: k8s.gcr.io/metrics-server/metrics-server
    tag: "v0.6.1"  # Verifique a versão mais recente
    pullPolicy: IfNotPresent

  # Argumentos para o Metrics Server
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname

  # Configurações de recursos (sobrescreve as configurações globais)
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  # Configurações de service account
  serviceAccount:
    create: true
    name: ""  # Se não definido, será gerado automaticamente

  # Configurações de segurança
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  # Configurações de tolerations para permitir execução em nós master
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule

  # Configurações de afinidade de nós
  affinity: {}

  # Configurações do serviço
  service:
    type: ClusterIP
    port: 443

  # Configurações de probes
  readinessProbe:
    httpGet:
      path: /readyz
      port: https
      scheme: HTTPS
    periodSeconds: 10
    failureThreshold: 3

  livenessProbe:
    httpGet:
      path: /livez
      port: https
      scheme: HTTPS
    periodSeconds: 10
    failureThreshold: 3

  # Configurações de rbac
  rbac:
    create: true

# Configurações de anotação e rótulo específicos para o ambiente de desenvolvimento
podLabels:
  environment: development

podAnnotations: {}

# Configurações adicionais
extraVolumeMounts: []
extraVolumes: []