apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 15.7.2
    valuesFile: values.yaml

resources:
  - service.yaml
  - ingress.yaml