apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring-{{name}}
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
