service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: true
  hosts:
    - name: prometheus.{{name}}.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  paths:
    - /
  pathType: Prefix
