service:
  enabled: true
  type: ClusterIP
  port: 9090

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: prometheus.local
      paths:
        - path: /
          pathType: Prefix
  tls: []