apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: develop
            cluster: https://kubernetes-cluster1.example.com
            namespace: monitoring-develop
          - name: sandbox
            cluster: https://kubernetes-cluster2.example.com
            namespace: monitoring-sandbox
  template:
    metadata:
      name: 'monitoring-{{name}}'
    spec:
      project: monitoring
      source:
        repoURL: 'https://github.com/pcnuness/gitops-poc.git'
        targetRevision: main
        path: 'cluster-management/monitoring/overlays/{{name}}'
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true