apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/pcnuness/gitops-poc.git'
        revision: main
        directories:
          - path: cluster-management/monitoring/overlays/dev
          - path: cluster-management/monitoring/overlays/stage
          - path: cluster-management/monitoring/overlays/prod
  template:
    metadata:
      name: 'monitoring-{{path.basename}}'
    spec:
      project: monitoring
      source:
        repoURL: 'https://github.com/pcnuness/gitops-poc.git'
        targetRevision: main
        path: 'cluster-management/monitoring/overlays/{{path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true