apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-applicationset
spec:
  generators:
    - git:
        repoURL: 'https://gitlab.com/seu-repo.git'
        revision: main
        directories:
          - path: cluster-management/monitoring/overlays/dev
          - path: cluster-management/monitoring/overlays/stage
          - path: cluster-management/monitoring/overlays/prod
  template:
    metadata:
      name: '{{path.basename}}-monitoring'
    spec:
      project: monitoring
      source:
        repoURL: 'https://gitlab.com/seu-repo.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
