apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/pcnuness/gitops-poc.git'  # Permitir repositório Git
  destinations:
    - namespace: 'monitoring-*'  # 🚀 Agora qualquer ambiente `monitoring-xyz` será permitido!
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      policies:
        - p, proj:monitoring, applications, sync, */*, allow
        - p, proj:monitoring, applications, get, */*, allow
      groups:
        - monitoring-admins