apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/pcnuness/gitops-poc.git'
  destinations:
    - namespace: monitoring-*
      server: https://kubernetes-cluster1.example.com
    - namespace: monitoring-*
      server: https://kubernetes-cluster2.example.com
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      policies:
        - p, proj:monitoring, applications, sync, */*, allow
        - p, proj:monitoring, applications, get, */*, allow
      groups:
        - monitoring-admins