apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: "Projeto para gerenciar aplicações de monitoramento"
  sourceRepos:
    - "https://github.com/pcnuness/gitops-poc.git"
  destinations:
    - namespace: monitoring-{{path.basename}}
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"