nameOverride:	cpe-mon
fullnameOverride: cpe-monitoring

nodeExporter:
  enabled: true
  operatingSystems:
    linux:
      enabled: true
    forceDeployDashboards: true

# Ingress do Prometheus (note o bloco 'server.ingress', conforme template oficial)
prometheus:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - prometheus.ops.905418282044.realhandsonlabs.net
    paths:
      - /

  prometheusSpec:
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
    externalUrl: https://prometheus.ops.905418282044.realhandsonlabs.net

# Ingress do Grafana
grafana:
  enabled: true
  adminPassword: prom-operator
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts: 
      - grafana.ops.905418282044.realhandsonlabs.net
    path: 
      - /
