# Arquivo values.yaml para o Helm Chart do kube-prometheus-stack
# Este arquivo é ajustado para ambientes de desenvolvimento.
# Inclui configurações padrão do kube-prometheus-stack com ajustes para recursos limitados.

# Configuração global
global:
  # Definindo o limite de recursos, típico para um ambiente de desenvolvimento
  resources:
    limits:
      cpu: 100m  # Limite de CPU
      memory: 256Mi  # Limite de memória
    requests:
      cpu: 50m  # Solicitação de CPU
      memory: 128Mi  # Solicitação de memória#
  namespaceOverride: observability

# Configuração para o Prometheus Operator
prometheusOperator:
  createCustomResource: true  # Habilita CRDs customizadas necessarias para o operador
  resources: {}  # Utiliza as configurações globais de recursos

# Configurações de anotação e rótulo específicos para o ambiente de desenvolvimento
# Estes rótulos ajudam a identificar e organizar as instâncias no cluster.
podLabels:
  environment: development  # Rótulo para identificar o ambiente de desenvolvimento

# Monitoramento e alertas básicos
prometheusRule:
  enabled: true  # Habilita regras de alertas padrão
  additionalPrometheusRulesMap: {}  # Mapa para regras adicionais se necessário

# Configuração do Prometheus
prometheus:
  prometheusSpec:
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/subnets: subnet-0687ad9e5d27708e8, subnet-097e8629e5a2d2e91, subnet-0db6a48503e1f7a92
      alb.ingress.kubernetes.io/listen-ports: '[{ "HTTP": 80, "HTTPS": 443 }]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:905418282044:certificate/695da736-395c-44a0-a2fb-8cb60a66a2e0
    hosts:
      - prometheus.ops.905418282044.realhandsonlabs.net
    paths:
      - /
    pathType: Prefix

# Configuração do Grafana
grafana:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/subnets: subnet-0687ad9e5d27708e8, subnet-097e8629e5a2d2e91, subnet-0db6a48503e1f7a92
      alb.ingress.kubernetes.io/listen-ports: '[{ "HTTP": 80, "HTTPS": 443 }]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:905418282044:certificate/695da736-395c-44a0-a2fb-8cb60a66a2e0
    paths:
      - /
    pathType: Prefix
    hosts:
      - grafana.ops.905418282044.realhandsonlabs.net