# Configuração global
global:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

## Prometheus
prometheus:
  server:
    ingress:
      enabled: true
      ingressClassName: alb
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internal
      hosts:
        - prometheus.ops.905418282044.realhandsonlabs.net
      paths:
        - /
      pathType: Prefix
      tls:
        - hosts:
            - prometheus.ops.905418282044.realhandsonlabs.net
          secretName: prometheus-tls
    resources:
      limits:
        cpu: 200m
        memory: 512Mi

## Grafana
grafana:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internal
    hosts:
      - grafana.ops.905418282044.realhandsonlabs.net
    paths:
      - /
    pathType: Prefix
    tls:
      - hosts:
          - grafana.ops.905418282044.realhandsonlabs.net
        secretName: grafana-tls
  env:
    GF_SERVER_ROOT_URL: https://grafana.ops.905418282044.realhandsonlabs.net
    GF_SERVER_SERVE_FROM_SUB_PATH: "true"

## (Opcional) Alertmanager
alertmanager:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internal
    hosts:
      - alertmanager.ops.905418282044.realhandsonlabs.net
    paths:
      - /
    pathType: Prefix
    tls:
      - hosts:
          - alertmanager.ops.905418282044.realhandsonlabs.net
        secretName: alertmanager-tls