# Configuração global
global:
  # Definindo o limite de recursos, típico para um ambiente de desenvolvimento
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  namespaceOverride: ""  # Deixe vazio para usar o namespace padrão da instalação

# Configuração para o Prometheus Operator
prometheusOperator:
  createCustomResource: true
  resources: {}

# Configurações de anotação e rótulo específicos para o ambiente de desenvolvimento
podLabels:
  environment: development

# Monitoramento e alertas básicos
prometheusRule:
  enabled: true
  additionalPrometheusRulesMap: {}

# Configuração do Prometheus
prometheus:
  ingress:  # Esta é a configuração correta para o Ingress do Prometheus
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.ops.905418282044.realhandsonlabs.net
    paths:
      - /
    pathType: Prefix
  prometheusSpec:
    resources:
      limits:
        cpu: 200m
        memory: 512Mi

# Configuração do Grafana
grafana:
  ingress:  # Esta é a configuração correta para o Ingress do Grafana
    enabled: true
    hosts:
      - grafana.ops.905418282044.realhandsonlabs.net
    paths:
      - /
    pathType: Prefix