# Configuração global
global:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

# Ingress do Prometheus (note o bloco 'server.ingress', conforme template oficial)
prometheus:
  # ESTE É O SUBCHART 'prometheus', não o chart-root
  server:
    ingress:
      enabled: true
      # Se sua versão de Kubernetes suporta ingressClassName diretamente:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      hosts:
        - prometheus.ops.905418282044.realhandsonlabs.net
      paths:
        - /
      tls:
        - hosts:
            - prometheus.ops.905418282044.realhandsonlabs.net
          secretName: prometheus-tls
    resources:
      limits:
        cpu: 200m
        memory: 512Mi

# Ingress do Grafana
grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - grafana.ops.905418282044.realhandsonlabs.net
    paths:
      - /