kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cpe-operation
nodes:
  - role: control-plane
    image: kindest/node:v1.31.0
    extraPortMappings:
      - containerPort: 443
        hostPort: 443
      - containerPort: 80
        hostPort: 80
    labels:
      ingress-ready: "true"
  - role: worker
    image: kindest/node:v1.31.0
    labels:
      tier: frontend
  - role: worker
    image: kindest/node:v1.31.0
    labels:
      tier: backend