apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-sandbox
namePrefix: sandbox-

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: grafana-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: grafana.sandbox.local
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: sandbox-observability-release-name-grafana