apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-develop
namePrefix: develop-

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: grafana-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: 80-port-g4plfhcbbpxtyjfy.labs.kodekloud.com
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: develop-observability-release-name-grafana