apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-develop
namePrefix: develop-

resources:
  - ../../base/prometheus

patches:
  #- target:
  #    kind: Ingress
  #    name: grafana-ingress
  #  patch: |-
  #    - op: replace
  #      path: /spec/rules/0/host
  #      value: grafana.develop.local
  #    - op: replace
  #      path: /spec/rules/0/http/paths/0/backend/service/name
  #      value: develop-observability-release-name-grafana
  - target:
      kind: Ingress
      name: prometheus-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: prometheus.develop.local
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: develop-observability-release-name-prometheus